stages:
  - build
  # - deploy

eleventy:
  stage: build
  image: node:lts-buster
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - node_modules/
  script:
    - npm install
    - npx @11ty/eleventy
  artifacts:
    paths:
      - public
  only:
    - master

# rsync:
#   stage: deploy
#   image: instrumentisto/rsync-ssh
#   script:
#   - mkdir "${HOME}/.ssh"
#   - echo "${SSH_HOST_KEY}" > "${HOME}/.ssh/known_hosts"
#   - echo "${SSH_PRIVATE_KEY}" > "${HOME}/.ssh/id_rsa"
#   - chmod 700 "${HOME}/.ssh/id_rsa"
#   - rsync -avH dist/* -e ssh ${SSH_USER}@${SSH_HOST}:${WEBROOT_PATH}
#   only:
#   - master
