image: node:lts-buster

stages:
  - build
  - deploy

cache:
  key: "$CI_JOB_NAME"
  paths:
    - node_modules/

npm:install:
  stage: build
  script:
    - npm install
  only:
    - master

eleventy:
  stage: build
  needs:
    - npm:install
  script:
    - npx @11ty/eleventy --output=public
  artifacts:
    paths:
      - public
  only:
    - master
